### PR TITLE
Add support for testing with lightning (`trainer.test`)

### PR DESCRIPTION
**Pull request by danielgafni**
### Description

 - Add test_step and test_epoch_end callbacks to base model
 - Add a better way to determine current trainer stage for logging (`current_stage` property)

### Checklist

- [x] Linked issues (if existing)
- [x] Amended changelog for large changes (and added myself there as contributor)
- [x] Added/modified tests
- [x] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

Make sure to have fun coding!

### CODE REVIEW

**Review by jdb78 — DISMISSED** [review]
Nice changes. Think there are some minor issues with the tests - happy to merge once fixed.

**Comment by danielgafni** [comment]
Hey! I've fixed the small bug. 
I also notices how `pre-commit` wasn't specified in the dev dependencies, so I added it. Is this ok? 

Also, I've made a Dockerfile for pytorch-forecasting. Actually, I did if for testing with ubuntu and python 3.7, because originally I thought the tests failed in this specific case lol. 

Do you want me to add this Dockerfile in another PR @jdb78 ?
It includes a `--build-arg PYTHON_VERSION` and does `config virtualenvs.create false` inside, so all the dependencies are nicely installed in the default system environment.

**Comment by danielgafni** [comment]
Looks like the test job randomly failed: `Fatal Python error: Segmentation fault`

**Comment by danielgafni** [comment]
This happened again... I've run the tests locally and they pass. Do you know what's the problem in the CI @jdb78 ?

**Comment by jdb78** [comment]
Seems to be connected to the AdamW optimizer

**Comment by jdb78** [comment]
rebased on master

**Comment by danielgafni** [comment]
I saw you merged the `.val_dataloader` PR! Great! When are you going to release a patch with these two fixes?

**Pull request merged**
