### PR TITLE
Bug Fix for #1071: NHiTs encoder/decoder covariate size difference bug

### PR DESCRIPTION
**Pull request by bendavidsteel**
### Description

Fix for https://github.com/jdb78/pytorch-forecasting/issues/1071 and https://github.com/jdb78/pytorch-forecasting/issues/1065

### CODE REVIEW

**Review by jdb78 — COMMENTED** [review]
Can we add a test. Looks like it makes a lot of sense but would like to have a test for this as it is an actual change in the model

**Comment by bendavidsteel** [comment]
Sure! Added a new test for NHiTs, confirmed it fails on master and passes on my branch

**Review by jdb78 — DISMISSED** [review]
Great PR! thanks a lot

**Comment by bendavidsteel** [comment]
Thanks! Just fixed the linter problem, looks like you'll need to approve again to get the workflows to run

**Comment by manitadayon** [comment]
@ jdb78, it seems, the merge did not take effect or there has been an update to modify this behavior since it still throws an error when covariates for encoder and decoder are different in NHiTS. 
Initially, using the @bendavidsteel  code was working, now even his modified version is throwing the same error (I forked his branch and tested his code is working)
Wondering if anything/update is changed to the core model? or if someone can test the model behavior?

**Pull request merged**
