### PR TITLE
fixed NegativeBinomialLoss for use with TFT

### PR DESCRIPTION
**Pull request by domplexity**
### Description

this should enable NegativeBinomialLoss with TFT

any feedback or criticism more than welcome.

next steps I see:

- generalize to other DistributionLosses
- derive Quantiles analytically

### Checklist

- [ https://github.com/jdb78/pytorch-forecasting/issues/309] Linked issues (if existing)
- [ ] Amended changelog for large changes (and added myself there as contributor)
- [ ] Added/modified tests
- [x] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

Make sure to have fun coding!

### CODE REVIEW

**Comment by jdb78** [comment]
It would be useful to have enable this for all distribution losses and add tests to ensure it does work. Do you think this is possible?

**Comment by domplexity** [comment]
sounds good, will give it a go.

in `.to_(point)prediction` i am making use of the fact that one of the distribution_arguments in the implementation of the negative binomial is the mean. of course this does not generalize well to any distribution that could be "arbitrarily" parametrized. I could do something sampling based (as in to_quantiles) and leave it to the implementer of specific Distribution Losses  or the end user to use something else.

**Comment by domplexity** [comment]
ran into some larger issues. will not have time in the very near future so closing this PR for now. will come back, when done

**Comment by jmiller558** [comment]
Hello, 

Unfortunately, NegativeBinomialDistributionLoss no longer works with TFT in pytorch-forecasting 0.10.3.

The error started after Google Colab upgraded to python 3.8 causing my notebooks to automatically start running pytorch-forecasting 0.10.3.  Downgrading to python 3.7 and pytorch-forecasting 0.10.1 causes the error to go away. 

I have re-created the error in [this colab notebook](https://colab.research.google.com/drive/1ORSTdOOQXkyQWackLS9Dyuuq3STJItNZ#scrollTo=__8ciRBx1fgf) using the [TFT tutorial code](https://pytorch-forecasting.readthedocs.io/en/stable/tutorials/stallion.html) slightly adjusted to switch to NegativeBinomialDistributionLoss.

The same error also occurs on other datasets where I am running TFT with NegativeBinomialDistributionLoss. 

**Error message:**
ValueError: Expected parameter total_count (Tensor of shape (350, 6)) of distribution NegativeBinomial(total_count: torch.Size([350, 6]), probs: torch.Size([350, 6])) to satisfy the constraint GreaterThanEq(lower_bound=0), but found invalid values:
tensor([[ 27.3240,  25.7105,  25.1888,  25.4835,  28.0047,  18.8410],
        [ 24.8063,  23.3642,  22.9043,  23.0588,  25.0264,  16.8969],
        [ 18.9572,  17.7293,  17.4891,  17.1998,  19.3951,  12.7476],
        ...,
        [124.7026, 119.7774, 117.8373, 119.3506, 121.7064,  95.2277],
        [ 24.9350,  23.9966,  23.5536,  25.0558,  24.9452,  20.1810],
        [     nan,      nan,      nan,      nan,      nan,      nan]])

**Pull request closed without merging**
