### PR TITLE
Ensure `TorchNormalizer` transformation output type matches input type

### PR DESCRIPTION
**Pull request by lukemerrick**
### Description

Addresses #574 by avoiding type promotion from float32 -> float64 during `TorchNormalizer` transformations.

### Checklist

- [x] Linked issues (if existing)
- ~[] Amended changelog for large changes (and added myself there as contributor)~ --> just a bugfix here
- [x] Added/modified tests
- [x] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

Make sure to have fun coding! :heavy_check_mark:

### CODE REVIEW

**Comment by lukemerrick** [comment]
@jdb78 I hope you don't mind me just opening a PR here. My hope is that this is the quickest way to resolve #574 , which is affecting me, too.

**Review by jdb78 — DISMISSED** [review]
nice catch!

**Comment by lukemerrick** [comment]
My bad, totally forgot to re-run tests when I made the second fix more upstream (where the float32 -> float64 type promotion was happening), and I totally neglected the multivariate case. Tests are now passing locally, and the code is also maybe a tad more readable, too.

**Comment by lukemerrick** [comment]
@jdb78 Do you know what the codecov issue is? I don't think my changes should have affected `optim.py` at all...

**Comment by jdb78** [comment]
Sometimes codecov gets confused 😀

**Review by jdb78 — APPROVED** [review]

**Comment by lukemerrick** [comment]
:tada: :tada: :tada: 

Thanks for being so prompt and helpful with this!

**Comment by lukemerrick** [comment]
@jdb78 Is there anything I can do to speed along the release of v0.9.3? It would streamline things a lot for me and my collaborators if we could specify dependencies in terms of an official release instead of the git repo, but in order to do that we'd need a release with the latest bugfixes in it.

**Comment by jdb78** [comment]
Thanks for pointing out. Should get one out in the next 7 days

**Pull request merged**
