### PR TITLE
Bugfix/multi target TFT attribute error

### PR DESCRIPTION
**Pull request by JakeForsey**
### Description

This PR fixes a problem I had when using multiple targets and TFT

### Checklist

- [ ] Linked issues (if existing)
- [ ] Amended changelog for large changes (and added myself there as contributor)
- [ ] Added/modified tests
- [ ] Used pre-commit hooks when committing to ensure that code is compliant with hooks. Install hooks with `pre-commit install`.
      To run hooks independent of commit, execute `pre-commit run --all-files`

Make sure to have fun coding!

### CODE REVIEW

**Comment by jdb78** [comment]
Thanks for this PR! Could you explain what the error was, you encountered that this PR solves?

**Comment by JakeForsey** [comment]
> Thanks for this PR! Could you explain what the error was, you encountered that this PR solves?

Working example that produces this error:
```
from pytorch_forecasting.models.temporal_fusion_transformer import TemporalFusionTransformer
from pytorch_forecasting.data import TimeSeriesDataSet
import pandas as pd
df = pd.DataFrame({"time_idx": range(10), "target1": range(10), "target2": range(10), "group_ids": [1 for _ in range(10)]})
ds = TimeSeriesDataSet(df, target=["target1", "target2"], time_idx="time_idx", group_ids=["group_ids"], min_encoder_length=5, max_prediction_length=5)
model = TemporalFusionTransformer.from_dataset(ds)
Traceback (most recent call last):
  File "/home/jakef/.virtualenvs/pytorch-forecasting/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-ad6a9f006765>", line 1, in <module>
    model = TemporalFusionTransformer.from_dataset(ds)
  File "/home/jakef/Development/open-source/pytorch-forecasting/pytorch_forecasting/models/temporal_fusion_transformer/__init__.py", line 364, in from_dataset
    for normalizer, l in zip(dataset.target_normalizer.normalizers, loss.metrics)
  File "/home/jakef/.virtualenvs/pytorch-forecasting/lib/python3.8/site-packages/torch/nn/modules/module.py", line 778, in __getattr__
    raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
torch.nn.modules.module.ModuleAttributeError: 'QuantileLoss' object has no attribute 'metrics'
```

```
git rev-parse HEAD
6cd116e0ff1b6c67487e7ea03e5af9373ea9d28c
```

**Comment by jdb78** [comment]
Ah. I think what is needed is an adjustment of the default loss function to convert to a multiloss if not already one in case of multiple targets.

**Review by jdb78 — APPROVED** [review]

**Comment by jdb78** [comment]
@JakeForsey Does my change solve your issue? Feel free to merge this if yes.

**Comment by JakeForsey** [comment]
> @JakeForsey Does my change solve your issue? Feel free to merge this if yes.

Checked locally, works, thank you.

I don't seem to be able to merge

**Pull request merged**
